from pathlib import Path
import sys

output_path = Path('js/input_files.js')
with output_path.open('w') as outfile:
    outfile.write(f'// This file was autogenerated by {sys.argv[0]};\n')
    outfile.write(f'// do not edit directly!\n\n')
    outfile.write('const INPUT_FILES = {\n')
    for txt_file in sorted(Path('InputFiles').glob('*.txt')):
        with txt_file.open() as f:
            outfile.write(f'    {txt_file.stem!r}: {{\n')
            num_segs = int(f.readline())
            x_min, y_min, x_max, y_max = [float(x) for x in f.readline().split()]
            outfile.write('        ')
            outfile.write(f'x_min: {x_min}, ')
            outfile.write(f'y_min: {y_min}, ')
            outfile.write(f'x_max: {x_max}, ')
            outfile.write(f'y_max: {y_max},\n')
            outfile.write('        segments: [\n')
            for line in f:
                if line.strip() != '':
                    x1, y1, x2, y2 = [float(x) for x in line.split()]
                    outfile.write(f'            {{x1: {x1}, y1: {y1}, x2: {x2}, y2: {y2}}},\n')
            outfile.write('        ],\n')
        outfile.write('    },\n')
    outfile.write('};\n')

print(f'Wrote {output_path}')
